# Generated by Django 4.2.3 on 2023-09-18 12:04

from django.db import migrations
from django.contrib.auth.models import Group


def create_default_groups(apps, schema_editor):
    Group.objects.get_or_create(name="student")
    Group.objects.get_or_create(name="teacher")
    Group.objects.get_or_create(name="canteen_staff")
    Group.objects.get_or_create(name="library_staff")

    # Add more groups as needed


class Migration(migrations.Migration):
    dependencies = [
        # Add any dependencies here if needed
    ]

    operations = [
        migrations.RunPython(create_default_groups),
    ]
