# Generated by Django 4.2.3 on 2023-11-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_customuser_class_stream"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="class_name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="stream",
            name="stream_name",
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
