# Generated by Django 4.2.3 on 2024-04-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_class_class_name_alter_stream_stream_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="class_name",
            field=models.CharField(
                choices=[("FY", "FY"), ("SY", "SY"), ("TY", "TY"), ("NA", "NA")],
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="stream",
            name="stream_name",
            field=models.CharField(
                choices=[
                    ("B.C.A", "B.C.A"),
                    ("B.sc", "B.sc"),
                    ("B.com", "B.com"),
                    ("BA", "BA"),
                    ("BBA", "BBA"),
                ],
                max_length=225,
                unique=True,
            ),
        ),
    ]
