# Generated by Django 4.2.3 on 2024-04-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_class_class_name_alter_stream_stream_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="class_name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="stream",
            name="stream_name",
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
