# Generated by Django 4.2.3 on 2024-04-26 04:05

from django.db import migrations
from accounts.models import Class, Stream, ClassStream


def create_default_class(apps, schema_editor):
    Class.objects.get_or_create(class_name="FY")
    Class.objects.get_or_create(class_name="SY")
    Class.objects.get_or_create(class_name="TY")
    Class.objects.get_or_create(class_name="NA")


def create_default_stream(app, schema_editor):
    for stream in ["BCA", "BBA", "B.sc", "B.com", "BA"]:
        s, _ = Stream.objects.get_or_create(stream_name=stream)
        for class_ in Class.objects.all():
            ClassStream.objects.get_or_create(stream_name=s, class_name=class_)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_class_class_name_alter_stream_stream_name"),
    ]

    operations = [
        migrations.RunPython(create_default_class),
        migrations.RunPython(create_default_stream),
    ]
