# Generated by Django 4.2.3 on 2024-04-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_subevent_rules_n_judging_cordinator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subevent",
            name="img",
            field=models.ImageField(
                default="default/default.png", upload_to="media/events"
            ),
        ),
    ]
