# Generated by Django 4.2.3 on 2023-12-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_event_user_id_alter_subevent_event_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="subevent",
            name="desc",
            field=models.TextField(default="hello world"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subevent",
            name="img",
            field=models.ImageField(
                default="media/default.png", upload_to="media/events"
            ),
        ),
    ]
