# Generated by Django 4.2.3 on 2023-12-17 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_subevent_desc_subevent_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("college", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=100)),
                (
                    "sub_event_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.subevent",
                    ),
                ),
            ],
        ),
    ]
