# Generated by Django 4.2.3 on 2023-12-17 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_participant"),
    ]

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("college_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("token", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="participant",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="events.college"
            ),
        ),
    ]
