# Generated by Django 4.2.3 on 2023-12-20 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_college_alter_participant_college"),
    ]

    operations = [
        migrations.AddField(
            model_name="college",
            name="event_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="events.event",
            ),
            preserve_default=False,
        ),
    ]
