# Generated by Django 4.2.3 on 2023-12-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_college_event_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="college",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
