# Generated by Django 4.2.3 on 2024-01-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_alter_college_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="subevent",
            name="brochure",
            field=models.FileField(default="null", upload_to="docs"),
            preserve_default=False,
        ),
    ]
