# Generated by Django 4.2.3 on 2023-12-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canteen", "0002_cart_alter_menu_image_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="items_id",
            field=models.ManyToManyField(through="canteen.Items", to="canteen.menu"),
        ),
    ]
