# Generated by Django 4.2.3 on 2023-12-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canteen", "0003_alter_cart_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
