# Generated by Django 4.2.3 on 2023-12-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canteen", "0004_items_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="image",
            field=models.ImageField(
                default="media/default.png", upload_to="media/canteen"
            ),
        ),
    ]
