# Generated by Django 4.2.3 on 2024-02-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canteen", "0005_alter_menu_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="image",
            field=models.ImageField(
                default="media/default.jpg", upload_to="media/canteen"
            ),
        ),
    ]
