# Generated by Django 4.2.3 on 2024-04-24 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("canteen", "0008_order_order_id_order_payment_id_order_signature_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_id",
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment_id",
        ),
        migrations.RemoveField(
            model_name="order",
            name="signature",
        ),
        migrations.AddField(
            model_name="order",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pay_order_id", models.CharField(max_length=255, null=True)),
                ("payment_id", models.CharField(max_length=255, null=True)),
                ("signature", models.CharField(max_length=500, null=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="canteen.order",
                    ),
                ),
            ],
        ),
    ]
