# Generated by Django 4.2.3 on 2024-04-25 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("canteen", "0009_remove_order_order_id_remove_order_payment_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="canteen.order"
            ),
        ),
    ]
