# Generated by Django 4.2.3 on 2023-11-26 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_class_classstream_alter_customuser_group_stream_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="class_stream",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="accounts.classstream",
            ),
        ),
    ]
